# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: new/system_wrapper.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0/system_signal_split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_1_0/system_axis_constant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_1_0 || ORIG_REF_NAME==system_axis_constant_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_1/system_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_1 || ORIG_REF_NAME==system_xlconcat_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_dac_ed_0_0/system_axis_dac_ed_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_dac_ed_0_0 || ORIG_REF_NAME==system_axis_dac_ed_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_2_0 || ORIG_REF_NAME==system_clk_wiz_2_0} -quiet] -quiet

# IP: bd/system/ip/system_carredephase180max_0_0/system_carredephase180max_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_carredephase180max_0_0 || ORIG_REF_NAME==system_carredephase180max_0_0} -quiet] -quiet

# IP: bd/system/ip/system_carredephase180max_0_0/carredephase180max_c_counter_binary_v12_0_i0/carredephase180max_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==carredephase180max_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==carredephase180max_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/system/ip/system_deMux_0_0/system_deMux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_deMux_0_0 || ORIG_REF_NAME==system_deMux_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/system_fmloopb05to8pas05_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fmloopb05to8pas05_0_0 || ORIG_REF_NAME==system_fmloopb05to8pas05_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i0/fmloopb05to8pas05_blk_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i0 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i0} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i1/fmloopb05to8pas05_blk_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i1 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i1} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i10/fmloopb05to8pas05_blk_mem_gen_i10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i10 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i10} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i11/fmloopb05to8pas05_blk_mem_gen_i11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i11 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i11} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i12/fmloopb05to8pas05_blk_mem_gen_i12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i12 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i12} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i13/fmloopb05to8pas05_blk_mem_gen_i13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i13 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i13} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i14/fmloopb05to8pas05_blk_mem_gen_i14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i14 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i14} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i15/fmloopb05to8pas05_blk_mem_gen_i15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i15 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i15} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i2/fmloopb05to8pas05_blk_mem_gen_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i2 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i2} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i3/fmloopb05to8pas05_blk_mem_gen_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i3 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i3} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i4/fmloopb05to8pas05_blk_mem_gen_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i4 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i4} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i5/fmloopb05to8pas05_blk_mem_gen_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i5 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i5} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i6/fmloopb05to8pas05_blk_mem_gen_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i6 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i6} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i7/fmloopb05to8pas05_blk_mem_gen_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i7 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i7} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i8/fmloopb05to8pas05_blk_mem_gen_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i8 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i8} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i9/fmloopb05to8pas05_blk_mem_gen_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_blk_mem_gen_i9 || ORIG_REF_NAME==fmloopb05to8pas05_blk_mem_gen_i9} -quiet] -quiet

# IP: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_c_counter_binary_v12_0_i0/fmloopb05to8pas05_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmloopb05to8pas05_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==fmloopb05to8pas05_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_3_0 || ORIG_REF_NAME==system_util_ds_buf_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1/system_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1 || ORIG_REF_NAME==system_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/system_amloopm01to1pas01_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_amloopm01to1pas01_0_0 || ORIG_REF_NAME==system_amloopm01to1pas01_0_0} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i0/amloopm01to1pas01_blk_mem_gen_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i0 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i0} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i1/amloopm01to1pas01_blk_mem_gen_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i1 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i1} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i2/amloopm01to1pas01_blk_mem_gen_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i2 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i2} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i3/amloopm01to1pas01_blk_mem_gen_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i3 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i3} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i4/amloopm01to1pas01_blk_mem_gen_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i4 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i4} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i5/amloopm01to1pas01_blk_mem_gen_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i5 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i5} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i6/amloopm01to1pas01_blk_mem_gen_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i6 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i6} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i7/amloopm01to1pas01_blk_mem_gen_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i7 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i7} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i8/amloopm01to1pas01_blk_mem_gen_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i8 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i8} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i9/amloopm01to1pas01_blk_mem_gen_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_blk_mem_gen_i9 || ORIG_REF_NAME==amloopm01to1pas01_blk_mem_gen_i9} -quiet] -quiet

# IP: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_c_counter_binary_v12_0_i0/amloopm01to1pas01_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==amloopm01to1pas01_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==amloopm01to1pas01_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_1_0 || ORIG_REF_NAME==system_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_2_0 || ORIG_REF_NAME==system_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_2_0 || ORIG_REF_NAME==system_clk_wiz_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0_ooc.xdc

# XDC: bd/system/ip/system_carredephase180max_0_0/constrs/carredephase180max.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_carredephase180max_0_0 || ORIG_REF_NAME==system_carredephase180max_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i0/fmloopb05to8pas05_blk_mem_gen_i0_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i1/fmloopb05to8pas05_blk_mem_gen_i1_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i10/fmloopb05to8pas05_blk_mem_gen_i10_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i11/fmloopb05to8pas05_blk_mem_gen_i11_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i12/fmloopb05to8pas05_blk_mem_gen_i12_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i13/fmloopb05to8pas05_blk_mem_gen_i13_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i14/fmloopb05to8pas05_blk_mem_gen_i14_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i15/fmloopb05to8pas05_blk_mem_gen_i15_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i2/fmloopb05to8pas05_blk_mem_gen_i2_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i3/fmloopb05to8pas05_blk_mem_gen_i3_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i4/fmloopb05to8pas05_blk_mem_gen_i4_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i5/fmloopb05to8pas05_blk_mem_gen_i5_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i6/fmloopb05to8pas05_blk_mem_gen_i6_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i7/fmloopb05to8pas05_blk_mem_gen_i7_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i8/fmloopb05to8pas05_blk_mem_gen_i8_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i9/fmloopb05to8pas05_blk_mem_gen_i9_ooc.xdc

# XDC: bd/system/ip/system_fmloopb05to8pas05_0_0/constrs/fmloopb05to8pas05.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fmloopb05to8pas05_0_0 || ORIG_REF_NAME==system_fmloopb05to8pas05_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_3_0 || ORIG_REF_NAME==system_util_ds_buf_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_3_0 || ORIG_REF_NAME==system_util_ds_buf_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i0/amloopm01to1pas01_blk_mem_gen_i0_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i1/amloopm01to1pas01_blk_mem_gen_i1_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i2/amloopm01to1pas01_blk_mem_gen_i2_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i3/amloopm01to1pas01_blk_mem_gen_i3_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i4/amloopm01to1pas01_blk_mem_gen_i4_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i5/amloopm01to1pas01_blk_mem_gen_i5_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i6/amloopm01to1pas01_blk_mem_gen_i6_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i7/amloopm01to1pas01_blk_mem_gen_i7_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i8/amloopm01to1pas01_blk_mem_gen_i8_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i9/amloopm01to1pas01_blk_mem_gen_i9_ooc.xdc

# XDC: bd/system/ip/system_amloopm01to1pas01_0_0/constrs/amloopm01to1pas01.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_amloopm01to1pas01_0_0 || ORIG_REF_NAME==system_amloopm01to1pas01_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_1_0 || ORIG_REF_NAME==system_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_1_0 || ORIG_REF_NAME==system_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
