# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.cache/wt [current_project]
set_property parent.project_path E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/RedPitaya/fpga/prj/Examples/Frequency_counter/tmp/cores
  c:/Users/Edward/Documents/MATLAB/phasecarre180max/ip
  c:/Users/Edward/Documents/MATLAB/Fm_loopB05to8pas05/ip
  c:/Users/Edward/Documents/MATLAB/AMloopm01to1pas01final/ip
  c:/Users/Edward/Documents/MATLAB/AM1M1Hzloopm01to1pas01final/ip
  c:/Users/Edward/Documents/MATLAB/AM_Multip_avec_gain/ip
  c:/Users/Edward/Documents/MATLAB/AM_Multip_avec_gainV3/ip
} [current_project]
set_property ip_output_repo e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define TOOL_VIVADO [current_fileset]
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i0_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i1_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i10_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i11_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i12_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i13_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i14_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i15_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i2_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i3_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i4_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i5_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i6_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i7_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i8_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i9_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i0_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i1_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i2_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i3_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i4_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i5_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i6_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i7_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i8_vivado.coe
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i9_vivado.coe
read_verilog -library xil_defaultlib {
  E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/imports/Frequency_counter/signal_split.v
  E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/new/axis_dac_ed.v
  E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/new/deMux.v
  E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
add_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_clk_wiz_2_0/system_clk_wiz_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_carredephase180max_0_0/constrs/carredephase180max.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i0/fmloopb05to8pas05_blk_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i1/fmloopb05to8pas05_blk_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i10/fmloopb05to8pas05_blk_mem_gen_i10_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i11/fmloopb05to8pas05_blk_mem_gen_i11_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i12/fmloopb05to8pas05_blk_mem_gen_i12_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i13/fmloopb05to8pas05_blk_mem_gen_i13_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i14/fmloopb05to8pas05_blk_mem_gen_i14_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i15/fmloopb05to8pas05_blk_mem_gen_i15_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i2/fmloopb05to8pas05_blk_mem_gen_i2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i3/fmloopb05to8pas05_blk_mem_gen_i3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i4/fmloopb05to8pas05_blk_mem_gen_i4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i5/fmloopb05to8pas05_blk_mem_gen_i5_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i6/fmloopb05to8pas05_blk_mem_gen_i6_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i7/fmloopb05to8pas05_blk_mem_gen_i7_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i8/fmloopb05to8pas05_blk_mem_gen_i8_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/fmloopb05to8pas05_blk_mem_gen_i9/fmloopb05to8pas05_blk_mem_gen_i9_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_fmloopb05to8pas05_0_0/constrs/fmloopb05to8pas05.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_util_ds_buf_3_0/system_util_ds_buf_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i0/amloopm01to1pas01_blk_mem_gen_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i1/amloopm01to1pas01_blk_mem_gen_i1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i2/amloopm01to1pas01_blk_mem_gen_i2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i3/amloopm01to1pas01_blk_mem_gen_i3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i4/amloopm01to1pas01_blk_mem_gen_i4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i5/amloopm01to1pas01_blk_mem_gen_i5_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i6/amloopm01to1pas01_blk_mem_gen_i6_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i7/amloopm01to1pas01_blk_mem_gen_i7_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i8/amloopm01to1pas01_blk_mem_gen_i8_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/amloopm01to1pas01_blk_mem_gen_i9/amloopm01to1pas01_blk_mem_gen_i9_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_amloopm01to1pas01_0_0/constrs/amloopm01to1pas01.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all e:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/ports_ed/imports/cfg/clocks.xdc
set_property used_in_implementation false [get_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/ports_ed/imports/cfg/clocks.xdc]

read_xdc E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/ports_ed/new/system_wrapper.xdc
set_property used_in_implementation false [get_files E:/VIVADO_FPGA/RedPitaya_v1.0/RedPitaya_v1.0.srcs/ports_ed/new/system_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top system_wrapper -part xc7z010clg400-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
